name: Create ZIP files

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create ZIP files
        run: |
          zip -r midi2osc-${{ github.ref_name }}.zip midi2osc
          zip -r osc_receiver_demo-${{ github.ref_name }}.zip osc_receiver_demo
      - name: Upload ZIP
        uses: softprops/action-gh-release@v2
        with:
          files: |
            midi2osc-${{ github.ref_name }}.zip
            osc_receiver_demo-${{ github.ref_name }}.zip
